<?php

namespace App\Helpers;

class Dictionary
{
    public $vocab = [
        "1" => [
            ['Sugeng', 'Selamat', '1'], ['Enjing', 'Pagi', '2'], ['Siang', 'Siang', '3'], ['Sonten', 'Sore', '4'], ['Ndalu', 'Malam', '5'], ['Rawuh', 'Datang', '6'], ['Pripun', 'Bagaimana', '7'], ['Piye', 'Bagaimana', '8'], ['Kabare', 'Kabar', '9'], ['Apik', 'Baik', '10'], ['Matur', 'Terima', '11'], ['Nuwun', 'Kasih', '12'], ['Sae', 'Baik', '13'], ['Biasa', 'Biasa', '14'], ['Wae', 'Saja', '15'], ['Suwe', 'Lama', '16'], ['Ora', 'Tidak', '17'], ['Ketemu', 'Bertemu', '18'], ['Aku', 'Aku', '19'], ['Kangen', 'Rindu', '20'], ['Kowe', 'Kamu', '21'], ['Ana', 'Ada', '22'], ['Kabar', 'Kabar', '23'], ['Apa', 'Apa', '24'], ['Sami-sami', 'Sama-sama', '25'], ['Mangga', 'Silahkan', '26'], ['Pinarak', 'Masuk', '27']
        ],
        "2" => [
            ['Kula nuwun', 'Permisi', '1'], ['Nuwun sewu', 'Permisi', '2'], ['Nami', 'Nama', '3'], ['Asma', 'Nama', '4'], ['Kula', 'Saya', '5'], ['Budi', 'Budi', '6'], ['Adi', 'Adi', '7'], ['Lair', 'Lahir', '8'], ['Ing', 'Di', '9'], ['Suroboyo', 'Surabaya', '10'], ['Panjenengan', 'Anda', '11'], ['Saking', 'Dari', '12'], ['Pundi', 'Mana', '13'], ['Sakniki', 'Sekarang', '14'], ['Sampun', 'Sudah', '15'], ['Umur', 'Umur', '16'], ['16', '16', '17'], ['Taun', 'Tahun', '18'], ['Sopo', 'Siapa', '19'], ['Sinten', 'Siapa', '20'], ['Bapak', 'Ayah', '21'], ['Ibuk', 'Ibu', '22'], ['Dalem', 'Rumah', '23'], ['Teng pundi', 'Dimana', '24']
        ],
        "3" => [
            ['Aku', 'Saya', 'A'], ['Kowe', 'Kamu', 'B'], ['Awakdhewe', 'Kita', 'C'], ['Deweke', 'Dia', 'D'], ['Iki', 'Ini', 'E'], ['Iku', 'Itu', 'F'], ['Opo', 'Apa', 'G'], ['Kapan', 'Kapan', 'H'], ['Ngendhi', 'Dimana', 'I'], ['Sing endhi', 'Yang mana', 'J'], ['Sopo', 'Siapa', 'K'], ['Ngopo', 'Mengapa', 'L'],  ['Yo', 'Ya', 'N'], ['Ora', 'Tidak', 'O'], ['Menowo', 'Barangkali', 'P'], ['Siji', 'Satu', 'Q'], ['Loro', 'Dua', 'R'], ['Telu', 'Tiga', 'S'], ['Papat', 'Empat', 'T'], ['Dalan', 'Jalan', 'U'], ['Kiro-kiro', 'Kira-kira', 'V'], ['Kabeh', 'Semua', 'W'], ['Luwih', 'Lebih', 'X'], ['Banget', 'Sangat', 'Y'], ['Anyar', 'Baru', 'Z'], ['Wingi', 'Kemarin', 'AA'], ['Lara', 'Sakit', 'AB'], ['Ngapunten', 'Maaf', 'AC'], ['Esuk', 'Pagi', 'AD'], ['Awan', 'Siang', 'AE'], ['Bengi', 'Malam', 'AF'], ['Piro', 'Berapa', 'AG'], ['Monggo', 'Silahkan', 'AH'], ['Nuwun', 'Terima kasih', 'AI'], ['Teko', 'Datang', 'AJ'], ['Mlaku', 'Berjalan', 'AK'], ['Omong', 'Bicara', 'AL'], ['Ngomong', 'Bilang', 'AM'], ['Ndelok', 'Melihat', 'AN'], ['Ngerti', 'Mengerti', 'AO'], ['Mangan', 'Makan', 'AP'], ['Ngombe', 'Minum', 'AQ'], ['Krungu', 'Mendengar', 'AR'], ['Wenehi', 'Memberi', 'AS'], ['Seneng', 'Suka', 'AT'], ['Pikir', 'Berpikir', 'AU'], ['Nggawe', 'Membuat', 'AV'], ['Lungguh', 'Duduk', 'AW'], ['Tugel', 'Patah', 'AX'], ['Tuku', 'Beli', 'AY'], ['Mandheg', 'Berhenti', 'AZ'], ['Kali']
        ]
    ];

    // public const vocab1 = [
    //     "ngoko" => [
    //         "1" => [
    //             ['Aku', 'Saya', 'A'], ['Kowe', 'Kamu', 'B'], ['Awakdhewe', 'Kita', 'C'], ['Deweke', 'Dia', 'D'], ['Iki', 'Ini', 'E'], ['Iku', 'Itu', 'F'], ['Opo', 'Apa', 'G'], ['Kapan', 'Kapan', 'H'], ['Ngendhi', 'Dimana', 'I'], ['Sing endhi', 'Yang mana', 'J'], ['Sopo', 'Siapa', 'K'], ['Ngopo', 'Mengapa', 'L'], ['Piye', 'Bagaimana', 'M'], ['Yo', 'Ya', 'N'], ['Ora', 'Tidak', 'O'], ['Menowo', 'Barangkali', 'P'], ['Siji', 'Satu', 'Q'], ['Loro', 'Dua', 'R'], ['Telu', 'Tiga', 'S'], ['Papat', 'Empat', 'T'], ['Dalan', 'Jalan', 'U'], ['Kiro-kiro', 'Kira-kira', 'V'], ['Kabeh', 'Semua', 'W'], ['Luwih', 'Lebih', 'X'], ['Banget', 'Sangat', 'Y'], ['Anyar', 'Baru', 'Z'], ['Wingi', 'Kemarin', 'AA'], ['Lara', 'Sakit', 'AB'], ['Ngapunten', 'Maaf', 'AC'], ['Esuk', 'Pagi', 'AD'], ['Awan', 'Siang', 'AE'], ['Bengi', 'Malam', 'AF'], ['Piro', 'Berapa', 'AG'], ['Monggo', 'Silahkan', 'AH'], ['Nuwun', 'Terima kasih', 'AI'], ['Teko', 'Datang', 'AJ'], ['Mlaku', 'Berjalan', 'AK'], ['Omong', 'Bicara', 'AL'], ['Ngomong', 'Bilang', 'AM'], ['Ndelok', 'Melihat', 'AN'], ['Ngerti', 'Mengerti', 'AO'], ['Mangan', 'Makan', 'AP'], ['Ngombe', 'Minum', 'AQ'], ['Krungu', 'Mendengar', 'AR'], ['Wenehi', 'Memberi', 'AS'], ['Seneng', 'Suka', 'AT'], ['Pikir', 'Berpikir', 'AU'], ['Nggawe', 'Membuat', 'AV'], ['Lungguh', 'Duduk', 'AW'], ['Tugel', 'Patah', 'AX'], ['Tuku', 'Beli', 'AY'], ['Mandheg', 'Berhenti', 'AZ'],
    //         ],
    //     ],

    //     "kromo" => [
    //         "1" => [
    //             ['Sugeng', 'Selamat', '1'], ['Enjing', 'Pagi', '2'], ['Siang', 'Siang', '3'], ['Sonten', 'Sore', '4'], ['Ndalu', 'Malam', '5'], ['Rawuh', 'Datang', '6'],
    //         ]
    //     ],
    // ];

    /* TODO Perbarui Content Sampai 5 Unit, Perbarui [Jawaban, Soal, Arti](indo-jawa)
    ** U1 Greetings, U2 Introduce, U3 Time, U4 Direction, U5 Describe Item,
    */

    public $jawaban = [
        "U1" => [
            ['Selamat', '1'], ['Pagi', '2'], ['Siang', '3'], ['Sore', '4'], ['Malam', '5'], ['Datang', '6'], ['Bagaimana', '7'], ['Bagaimana', '8'], ['Kabar', '9'], ['Baik', '10'], ['Terima', '11'], ['Kasih', '12'], ['Baik', '13'], ['Biasa', '14'], ['Saja', '15'], ['Lama', '16'], ['Tidak', '17'], ['Bertemu', '18'], ['Aku', '19'], ['Rindu', '20'], ['Kamu', '21'], ['Ada', '22'], ['Kabar', '23'], ['Apa', '24'], ['Sama-sama', '25'], ['Silahkan', '26'], ['Masuk', '27'],
            ['Sugeng', '28'], ['Enjing', '29'], ['Siang', '30'], ['Sonten', '31'], ['Ndalu', '32'], ['Rawuh', '33'], ['Pripun', '34'], ['Piye', '35'], ['Kabare', '36'], ['Apik', '37'], ['Matur', '38'], ['Nuwun', '39'], ['Sae', '40'], ['Biasa', '41'], ['Wae', '42'], ['Suwe', '43'], ['Ora', '44'], ['Ketemu', '45'], ['Aku', '46'], ['Kangen', '47'], ['Kowe', '48'], ['Ana', '49'], ['Kabar', '50'], ['Apa', '51'], ['Sami-sami', '52'], ['Mangga', '53'], ['Pinarak', '54']
        ],
        "U2" => [
            ['Permisi', '1'], ['Permisi', '2'], ['Nama', '3'], ['Nama', '4'], ['Saya', '5'], ['Budi', '6'], ['Adi', '7'], ['Lahir', '8'], ['Di', '9'], ['Surabaya', '10'], ['Anda', '11'], ['Dari', '12'], ['Mana', '13'], ['Sekarang', '14'], ['Sudah', '15'], ['Umur', '16'], ['16', '17'], ['Tahun', '18'], ['Siapa', '19'], ['Siapa', '20'], ['Ayah', '21'], ['Ibu', '22'], ['Rumah', '23'], ['Dimana', '24'],
            ['Kula nuwun', '25'], ['Nuwun sewu', '26'], ['Nami', '27'], ['Asma', '28'], ['Kula', '29'], ['Budi', '30'], ['Adi', '31'], ['Lair', '32'], ['Ing', '33'], ['Suroboyo', '34'], ['Panjenengan', '35'], ['Saking', '36'], ['Pundi', '37'], ['Sakniki', '38'], ['Sampun', '39'], ['Umur', '40'], ['16', '41'], ['Taun', '42'], ['Sopo', '43'], ['Sinten', '44'], ['Bapak', '45'], ['Ibuk', '46'], ['Dalem', '47'], ['Teng pundi', '48']
        ],
        "U3" => [
            ['Pintu', '1a'], ['Jendela', '2a'], ['Kursi', '3a'], ['Meja', '4a'], ['Kursi Kecil', '5a'], ['Baju', '6a'], ['Celana', '7a'], ['Celana Panjang', '8a'], ['Kasur', '9a'], ['Selimut', '10a'], ['Gayung', '11a'], ['Air', '12a'], ['Rumah', '13a'], ['Atap', '14a'], ['Tangga', '15a'], ['Pisau', '16a'], ['Mangkok', '17a'], ['Cangkul', '18a'], ['Pohon', '19a'], ['Halaman', '20a'], ['Bunga', '21a'], ['Rumput', '22a'], ['Buah', '23a'], ['Daun', '24a'], ['Tanah', '25a'], ['Batu', '26a'], ['Hewan', '27a'], ['Ikan', '28a'], ['Burung', '29a'], ['Motor', '30a'], ['Kereta', '31a'], ['Perahu', '32a'], ['Pesawat', '33a'], ['Delman', '34a'], ['Uang', '35a'], ['Uang', '36a'], ['Dinding', '37a'], ['Handuk', '38a'], ['Nasi', '39a'], ['Minyak', '40a'], ['Telur', '41a'], ['Garam', '42a'], ['Satu', '43a'], ['Dua', '44a'], ['Tiga', '45a'], ['Empat', '46a'], ['Lima', '47a'], ['Enam', '48a'], ['Tujuh', '49a'], ['Delapan', '50a'], ['Sembilan', '51a'], ['Sepuluh', '52a'], ['Sebelas', '53a'], ['Dua Belas', '54a'], ['Tiga Belas', '55a'], ['Empat Belas', '56a'], ['Lima Belas', '57a'], ['Enam Belas', '58a'], ['Tujuh Belas', '59a'], ['Delapan Belas', '60a'], ['Sembilan Belas', '61a'], ['Dua Puluh', '62a'], ['Dua Puluh Satu', '63a'], ['Dua Puluh Dua', '64a'], ['Dua Puluh Tiga', '65a'], ['Dua Puluh Empat', '66a'], ['Dua Puluh Lima', '67a'], ['Dua Puluh Enam', '68a'], ['Tiga Puluh', '69a'], ['Tiga Puluh Satu', '70a'], ['Empat Puluh', '71a'], ['Empat Puluh Satu', '72a'], ['Lima Puluh', '73a'], ['Lima Puluh Satu', '74a'], ['Enam Puluh', '75a'], ['Enam Puluh Satu', '76a'], ['Tujuh Puluh', '77a'], ['Tujuh Puluh Satu', '78a'], ['Delapan Puluh', '79a'], ['Sembilan Puluh', '80a'], ['Ini', '81a'], ['Itu', '82a'], ['Apa', '83a'], ['Berapa', '84a'], ['Harga', '85a'], ['Bagus', '86a'], ['Kokoh', '87a'], ['Bersih', '89a'], ['Banyak', '90a'], ['Banyak', '91a'], ['Naik', '92a'], ['Naik', '93a'], ['Keras', '94a'], ['Lembut', '95a'], ['Sama', '96a'], ['Aku', '97a'], ['Ayah', '98a'], ['Ibu', '99a'], ['Nenek/Kakek', '100a'], ['Beli', '101a'], ['Beli', '102a'],
            ['Lawang', '1'], ['Jendhela', '2'], ['Kursi', '3'], ['Meja', '4'], ['Dingklik', '5'], ['Klambi', '6'], ['Kathok', '7'], ['Celono', '8'], ['Amben', '9'], ['Kemul', '10'], ['Ciduk', '11'], ['Banyu', '12'], ['Omah', '13'], ['Gendheng', '14'], ['Ondo', '15'], ['Piso', '16'], ['Tuwung', '17'], ['Pacul', '18'], ['Wit', '19'], ['Latar', '20'], ['Kembang', '21'], ['Suket', '22'], ['Woh', '23'], ['Godhong', '24'], ['Lemah', '25'], ['Watu', '26'], ['Kewan', '27'], ['Iwak', '28'], ['Manuk', '29'], ['Montor', '30'], ['Sepur', '31'], ['Prau', '32'], ['Montor Mabur', '33'], ['Dokar', '34'], ['Arto', '35'], ['Duwit', '36'], ['Tembok', '37'], ['Anduk', '38'], ['Sego', '39'], ['Lengo', '40'], ['Endog', '41'], ['Uyah', '42'], ['Siji', '43'], ['Loro', '44'], ['Telu', '45'], ['Papat', '46'], ['Limo', '47'], ['Enem', '48'], ['Pitu', '49'], ['Wolu', '50'], ['Sanga', '51'], ['Sepuluh', '52'], ['Sewelas', '53'], ['Rolas', '54'], ['Telulas', '55'], ['Patbelas', '56'], ['Limolas', '57'], ['Nembelas', '58'], ['Pitulas', '59'], ['Wolulas', '60'], ['Sangalas', '61'], ['Rongpuluh', '62'], ['Selikur', '63'], ['Rolikur', '64'], ['Telulikur', '65'], ['Patlikur', '66'], ['Selawe', '67'], ['Nemlikur', '68'], ['Telungpuluh', '69'], ['Telungpuluh Siji', '70'], ['Patangpuluh', '71'], ['Patangpuluh Siji', '72'], ['Seket', '73'], ['Seket Siji', '74'], ['Sewidak', '75'], ['Sewidak Siji', '76'], ['Pitungpuluh', '77'], ['Pitungpuluh Siji', '78'], ['Wolungpuluh', '79'], ['Sangangpuluh', '80'], ['Iki', '81'], ['Iku', '82'], ['Opo', '83'], ['Piro', '84'], ['Rego', '85'], ['Apik', '86'], ['Kuwat', '87'], ['Resik', '89'], ['Akeh', '90'], ['Katah', '91'], ['Nitih', '92'], ['Numpak', '93'], ['Atos', '94'], ['Empuk', '95'], ['Karo', '96'], ['Aku', '97'], ['Bapak', '98'], ['Ibuk', '99'], ['Simbah', '100'], ['Tuku', '101'], ['Tumbas', '102']
        ],

    ];

    public $soal = [

        "U1P1" => [
            ['Sugeng', '1'], ['Enjing', '2'], ['Siang', '3'], ['Sonten', '4'], ['Ndalu', '5'], ['Rawuh', '6'], ['Pripun', '7'], ['Piye', '8'], ['Kabare', '9'], ['Apik', '10'], ['Matur', '11'], ['Nuwun', '12'], ['Sae', '13'], ['Biasa', '14'], ['Wae', '15'], ['Suwe', '16'], ['Ora', '17'], ['Ketemu', '18'], ['Aku', '19'], ['Kangen', '20'], ['Kowe', '21'], ['Ana', '22'], ['Kabar', '23'], ['Apa', '24'], ['Sami-sami', '25'], ['Mangga', '26'], ['Pinarak', '27'],
            ['Selamat', '28'], ['Pagi', '29'], ['Siang', '30'], ['Sore', '31'], ['Malam', '32'], ['Datang', '33'], ['Bagaimana', '34'], ['Bagaimana', '35'], ['Kabar', '36'], ['Baik', '37'], ['Terima', '38'], ['Kasih', '39'], ['Baik', '40'], ['Biasa', '41'], ['Saja', '42'], ['Lama', '43'], ['Tidak', '44'], ['Bertemu', '45'], ['Aku', '46'], ['Rindu', '47'], ['Kamu', '48'], ['Ada', '49'], ['Kabar', '50'], ['Apa', '51'], ['Sama-sama', '52'], ['Silahkan', '53'], ['Masuk', '54']
        ],
        "U1P2" => [
            ['Sugeng Enjing', '1 2'], ['Sugeng Siang', '1 3'], ['Sugeng Sonten', '1 4'], ['Sugeng Ndalu', '1 5'], ['Sugeng Rawuh', '1 6'], ['Piye kabare?', '8 9'], ['Pripun kabare?', '7 9'], ['Apik, Matur Suwun', '10 11 12'], ['Sae, Matur Nuwun', '13 11 12'], ['Biasa wae', '14 15'], ['Suwe ora ketemu', '16 17 18'], ['Aku kangen kowe', '19 20 21'], ['Ana kabar apa?', '22 23 24'], ['Sami-sami', '25'], ['Mangga pinarak', '26 27'],
            ['Selamat Datang', '28 29'], ['Selamat Siang', '28 30'], ['Selamat Sore', '28 31'], ['Selamat Malam', '28 32'], ['Selamat Datang', '28 33'], ['Bagaimana kabarnya?', '35 36'], ['Bagaimana kabarnya?', '34 36'], ['Baik, terima kasih', '37 38 39'], ['Baik, terima kasih', '40 38 39'], ['Biasa saja', '41 42'], ['Lama tidak bertemu', '43 44 45'], ['Aku rindu kamu', '46 47 48'], ['Ada kabar apa?', '49 50 51'], ['Sama-sama', '52'], ['Silahkan masuk', '53 54']
        ],
        "U2P1" => [
            ['Kula nuwun', '1'], ['Nuwun sewu', '2'], ['Nami', '3'], ['Asma', '4'], ['Kula', '5'], ['Budi', '6'], ['Adi', '7'], ['Lair', '8'], ['Ing', '9'], ['Suroboyo', '10'], ['Panjenengan', '11'], ['Saking', '12'], ['Pundi', '13'], ['Sakniki', '14'], ['Sampun', '15'], ['Umur', '16'], ['16', '17'], ['Taun', '18'], ['Sopo', '19'], ['Sinten', '20'], ['Bapak', '21'], ['Ibuk', '22'], ['Dalem', '23'], ['Teng pundi', '24'],
            ['Permisi', '25'], ['Permisi', '26'], ['Nama', '27'], ['Nama', '28'], ['Saya', '29'], ['Budi', '30'], ['Adi', '31'], ['Lahir', '32'], ['Di', '33'], ['Surabaya', '34'], ['Anda', '35'], ['Dari', '36'], ['Mana', '37'], ['Sekarang', '38'], ['Sudah', '39'], ['Umur', '40'], ['16', '41'], ['Tahun', '42'], ['Siapa', '43'], ['Siapa', '44'], ['Ayah', '45'], ['Ibu', '46'], ['Rumah', '47'], ['Dimana', '48']
        ],
        "U2P2" => [
            ['Nuwun sewu, Asma kula Budi', '2 4 5 6'], ['Kula lair ing Suroboyo', '5 8 9 10'], ['Panjenengan saking pundi?', '11 12 13'], ['Asma kula Adi', '2 4 7'], ['Nami kula Budi', '3 5 6'], ['Umur kula 16 taun', '16 5 17 18'], ['Sinten asmane panjenengan?', '20 4 11'], ['Dalem e panjenengan teng pundi?', '23 11 24'], ['Bapak teng pundi?', '21 24'], ['Ibuk teng pundi?', '22 24'], ['Panjenengan lair teng pundi?', '11 8 24'], ['Adi ing Suroboyo', '7 9 10'], ['Budi ing Suroboyo', '6 9 10'], ['Budi teng pundi?', '6 24'], ['Adi teng pundi?', '7 24'], ['Kula saking suroboyo', '5 12 10'], ['Nami kula Adi', '3 5 7'],
            ['Permisi, Nama saya Budi', '26 28 29 30'], ['Saya lahir di surabaya', '29 32 33 34'], ['Anda dari mana?', '35 36 37'], ['Nama saya Adi', '28 29 31'], ['Nama saya Budi', '27 29 30'], ['Umur saya 16 tahun', '40 29 41 42'], ['Siapa nama anda?', '44 28 35'], ['Rumah anda dimana?', '47 35 48'], ['Ayah dimana?', '45 48'], ['Ibu dimana?', '46 48'], ['Anda lahir dimana?', '35 32 48'], ['Adi di Surabaya', '31 33 34'], ['Budi di Surabaya', '30 33 34'], ['Budi dimana?', '30 48'], ['Adi dimana?', '31 48'], ['Saya dari surabaya', '29 36 34'], ['Nama saya Adi', '27 29 31']
        ],
        "U3P1" => [
            ['Lawang', '1a'], ['Jendhela', '2a'], ['Kursi', '3a'], ['Meja', '4a'], ['Dingklik', '5a'], ['Klambi', '6a'], ['Kathok', '7a'], ['Celono', '8a'], ['Amben', '9a'], ['Kemul', '10a'], ['Ciduk', '11a'], ['Banyu', '12a'], ['Omah', '13a'], ['Gendheng', '14a'], ['Ondo', '15a'], ['Piso', '16a'], ['Tuwung', '17a'], ['Pacul', '18a'], ['Wit', '19a'], ['Latar', '20a'], ['Kembang', '21a'], ['Suket', '22a'], ['Woh', '23a'], ['Godhong', '24a'], ['Lemah', '25a'], ['Watu', '26a'], ['Kewan', '27a'], ['Iwak', '28a'], ['Manuk', '29a'], ['Montor', '30a'], ['Sepur', '31a'], ['Prau', '32a'], ['Montor Mabur', '33a'], ['Dokar', '34a'], ['Arto', '35a'], ['Duwit', '36a'], ['Tembok', '37a'], ['Anduk', '38a'], ['Sego', '39a'], ['Lengo', '40a'], ['Endog', '41a'], ['Uyah', '42a'], ['Siji', '43a'], ['Loro', '44a'], ['Telu', '45a'], ['Papat', '46a'], ['Limo', '47a'], ['Enem', '48a'], ['Pitu', '49a'], ['Wolu', '50a'], ['Sanga', '51a'], ['Sepuluh', '52a'], ['Sewelas', '53a'], ['Rolas', '54a'], ['Telulas', '55a'], ['Patbelas', '56a'], ['Limolas', '57a'], ['Nembelas', '58a'], ['Pitulas', '59a'], ['Wolulas', '60a'], ['Sangalas', '61a'], ['Rongpuluh', '62a'], ['Selikur', '63a'], ['Rolikur', '64a'], ['Telulikur', '65a'], ['Patlikur', '66a'], ['Selawe', '67a'], ['Nemlikur', '68a'], ['Telungpuluh', '69a'], ['Telungpuluh Siji', '70a'], ['Patangpuluh', '71a'], ['Patangpuluh Siji', '72a'], ['Seket', '73a'], ['Seket Siji', '74a'], ['Sewidak', '75a'], ['Sewidak Siji', '76a'], ['Pitungpuluh', '77a'], ['Pitungpuluh Siji', '78a'], ['Wolungpuluh', '79a'], ['Sangangpuluh', '80a'], ['Iki', '81a'], ['Iku', '82a'], ['Opo', '83a'], ['Piro', '84a'], ['Rego', '85a'], ['Apik', '86a'], ['Kuwat', '87a'], ['Resik', '89a'], ['Akeh', '90a'], ['Katah', '91a'], ['Nitih', '92a'], ['Numpak', '93a'], ['Atos', '94a'], ['Empuk', '95a'], ['Karo', '96a'], ['Aku', '97a'], ['Bapak', '98a'], ['Ibuk', '99a'], ['Simbah', '100a'], ['Tuku', '101a'], ['Tumbas', '102a'],
            ['Pintu', '1'], ['Jendela', '2'], ['Kursi', '3'], ['Meja', '4'], ['Kursi Kecil', '5'], ['Baju', '6'], ['Celana', '7'], ['Celana Panjang', '8'], ['Kasur', '9'], ['Selimut', '10'], ['Gayung', '11'], ['Air', '12'], ['Rumah', '13'], ['Atap', '14'], ['Tangga', '15'], ['Pisau', '16'], ['Mangkok', '17'], ['Cangkul', '18'], ['Pohon', '19'], ['Halaman', '20'], ['Bunga', '21'], ['Rumput', '22'], ['Buah', '23'], ['Daun', '24'], ['Tanah', '25'], ['Batu', '26'], ['Hewan', '27'], ['Ikan', '28'], ['Burung', '29'], ['Motor', '30'], ['Kereta', '31'], ['Perahu', '32'], ['Pesawat', '33'], ['Delman', '34'], ['Uang', '35'], ['Uang', '36'], ['Dinding', '37'], ['Handuk', '38'], ['Nasi', '39'], ['Minyak', '40'], ['Telur', '41'], ['Garam', '42'], ['Satu', '43'], ['Dua', '44'], ['Tiga', '45'], ['Empat', '46'], ['Lima', '47'], ['Enam', '48'], ['Tujuh', '49'], ['Delapan', '50'], ['Sembilan', '51'], ['Sepuluh', '52'], ['Sebelas', '53'], ['Dua Belas', '54'], ['Tiga Belas', '55'], ['Empat Belas', '56'], ['Lima Belas', '57'], ['Enam Belas', '58'], ['Tujuh Belas', '59'], ['Delapan Belas', '60'], ['Sembilan Belas', '61'], ['Dua Puluh', '62'], ['Dua Puluh Satu', '63'], ['Dua Puluh Dua', '64'], ['Dua Puluh Tiga', '65'], ['Dua Puluh Empat', '66'], ['Dua Puluh Lima', '67'], ['Dua Puluh Enam', '68'], ['Tiga Puluh', '69'], ['Tiga Puluh Satu', '70'], ['Empat Puluh', '71'], ['Empat Puluh Satu', '72'], ['Lima Puluh', '73'], ['Lima Puluh Satu', '74'], ['Enam Puluh', '75'], ['Enam Puluh Satu', '76'], ['Tujuh Puluh', '77'], ['Tujuh Puluh Satu', '78'], ['Delapan Puluh', '79'], ['Sembilan Puluh', '80'], ['Ini', '81'], ['Itu', '82'], ['Apa', '83'], ['Berapa', '84'], ['Harga', '85'], ['Bagus', '86'], ['Kokoh', '87'], ['Bersih', '89'], ['Banyak', '90'], ['Banyak', '91'], ['Naik', '92'], ['Naik', '93'], ['Keras', '94'], ['Lembut', '95'], ['Sama', '96'], ['Aku', '97'], ['Ayah', '98'], ['Ibu', '99'], ['Nenek/Kakek', '100'], ['Beli', '101'], ['Beli', '102']
        ],
        "U3P2" => [
            ['Lawang e apik', '1a 86a'], ['Kursine kuwat', '3a 87a'], ['Mejane kuwat', '4a 87a'], ['Dingklik e kuwat', '5a 87a'], ['Klambine apik', '6a 86a'], ['Kathok e apik', '7a 86a'], ['Celonone apik', '8a 86a'], ['Amben e kuwat', '9a 87a'], ['Kemul e empuk', '10a 95a'], ['Banyune resik', '12a 89a'], ['Omah e resik', '13a 89a'], ['Omah e apik', '13a 86a'], ['Gendheng e kuwat', '14a 87a'], ['Wit e kuwat', '19a 87a'], ['Latar e resik', '20a 89a'], ['Suket e akeh', '22a 90a'], ['Suket e katah', '23a 91a'], ['Woh e akeh', '23a 90a'], ['Woh e katah', '23a 91a'], ['Woh e apik', '23a 86a'], ['Godhong e akeh', '24a 90a'], ['Godhong e katah', '24a 91a'], ['Watune akeh', '26a 90a'], ['Kewan e akeh', '27a 90a'], ['Iwak e akeh', '28a 90a'], ['Manuk e akeh', '29a 90a'], ['aku numpak montor', '93a 30a'], ['Bapak nitih montor', '98a 92a 30a'], ['Ibuk nitih montor', '99a 92a 30a'], ['Simbah nitih dokar', '100a 92a 34a'], ['Aku numpak dokar', '97a 93a 34a'], ['Ibuk nitih dokar', '99a 92a 34a'], ['Aku numpak sepur', '97a 93a 31a'], ['Bapak nitih sepur', '98a 92a 31a'], ['Ibuk nitih sepur', '99a 92a 31a'], ['Simbah nitih sepur', '100a 92a 31a'], ['Aku numpak prau', '97a 93a 32a'], ['Bapak nitih prau', '98a 92a 32a'], ['Ibuk nitih prau', '99a 92a 32a'], ['Simbah nitih prau', '100a 92a 32a'], ['Aku numpak montor mabur', '97a 93a 33a'], ['Bapak nitih montor mabur', '98a 92a 33a'], ['Ibuk nitih montor mabur', '99a 92a 33a'], ['Simbah nitih montor mabur', '100a 92a 33a'], ['Tembok e kuwat', '37a 87a'], ['Anduk e resik', '38a 89a'], ['Segone empuk', '39a 95a'], ['Segone atos', '39a 94a'],
            ['Pintunya bagus', '1 86'], ['Kursinya kokoh', '3 87'], ['Mejanya kokoh', '4 87'], ['Kursi (kecil)-nya kokoh', '5 87'], ['Bajunya bagus', '6 86'], ['Celananya bagus', '7 86'], ['Celana (Panjang)-nya bagus', '8 86'], ['Kasurnya kokoh', '9 87'], ['Selimutnya lembut', '10 95'], ['Airnya bersih', '12 89'], ['Rumahnya bersih', '13 89'], ['Rumahnya bagus', '13 86'], ['Atapnya kokoh', '14 87'], ['Pohonnya kokoh', '19 87'], ['Halamannya bersih', '20 89'], ['Rumputnya banyak', '22 90'], ['Rumputnya banyak', '23 91'], ['Buahnya banyak', '23 90'], ['Buahnya banyak', '23 91'], ['Buahnya bagus', '23 86'], ['Daunnya banyak', '24 90'], ['Daunnya banyak', '24 91'], ['Batunya banyak', '26 90'], ['Hewannya banyak', '27 90'], ['Ikannya banyak', '28 90'], ['Burungnya banyak', '29 90'], ['Aku naik motor', '93 30'], ['Ayah naik motor', '98 92 30'], ['Ibu naik motor', '99 92 30'], ['Kakek naik delman', '100 92 34'], ['Aku naik delman', '97 93 34'], ['Ibu naik delman', '99 92 34'], ['Aku naik kereta', '97 93 31'], ['Ayah naik kereta', '98 92 31'], ['Ibu naik kereta', '99 92 31'], ['Kakek naik kereta', '100 92 31'], ['Aku naik perahu', '97 93 32'], ['Ayah naik perahu', '98 92 32'], ['Ibu naik perahu', '99 92 32'], ['Kakek naik perahu', '100 92 32'], ['Aku naik pesawat', '97 93 33'], ['Ayah naik pesawat', '98 92 33'], ['Ibu naik pesawat', '99 92 33'], ['Kakek naik pesawat', '100 92 33'], ['Dindingnya kokoh', '37 87'], ['Handuknya bersih', '38 89'], ['Nasinya lembut', '39 95'], ['Nasinya keras', '39 94']
        ],
    ];

    public $arti = [
        "U1P1" => [
            ['Selamat'], ['Pagi'], ['Siang'], ['Sore'], ['Malam'], ['Datang'], ['Bagaimana'], ['Bagaimana'], ['Kabar'], ['Baik'], ['Terima'], ['Kasih'], ['Baik'], ['Biasa'], ['Saja'], ['Lama'], ['Tidak'], ['Bertemu'], ['Aku'], ['Rindu'], ['Kamu'], ['Ada'], ['Kabar'], ['Apa'], ['Sama-sama'], ['Silahkan'], ['Masuk'],
            ['Sugeng'], ['Enjing'], ['Siang'], ['Sonten'], ['Ndalu'], ['Rawuh'], ['Pripun'], ['Piye'], ['Kabare'], ['Apik'], ['Matur'], ['Nuwun'], ['Sae'], ['Biasa'], ['Wae'], ['Suwe'], ['Ora'], ['Ketemu'], ['Aku'], ['Kangen'], ['Kowe'], ['Ana'], ['Kabar'], ['Apa'], ['Sami-sami'], ['Mangga'], ['Pinarak']
        ],
        "U1P2" => [
            [55, 0, 'Selamat'], [55, 1, 'Pagi'], [56, 0, 'Selamat'], [56, 1, 'Siang'], [57, 0, 'Selamat'], [57, 1, 'Sore'], [58, 0, 'Selamat'], [58, 1, 'Malam'], [59, 0, 'Selamat'], [59, 1, 'Datang'], [60, 0, 'Bagaimana'], [60, 1, 'Kabarnya?'], [61, 0, 'Bagaimana'], [61, 1, 'Kabarnya?'], [62, 0, 'Baik'], [62, 1, 'Terima'], [62, 2, 'Kasih'], [63, 0, 'Baik'], [63, 1, 'Terima'], [63, 2, 'Kasih'], [64, 0, 'Biasa'], [64, 1, 'Saja'], [65, 0, 'Lama'], [65, 1, 'Tidak'], [65, 2, 'Bertemu'], [66, 0, 'Aku'], [66, 1, 'Rindu'], [66, 2, 'Kamu'], [67, 0, 'Ada'], [67, 1, 'Kabar'], [67, 2, 'Apa'], [68, 0, 'Sama-sama'], [69, 0, 'Silahkan'], [69, 1, 'Masuk'],
            [70, 0, 'Sugeng'], [70, 1, 'Enjing'], [71, 0, 'Sugeng'], [71, 1, 'Siang'], [72, 0, 'Sugeng'], [72, 1, 'Sonten'], [73, 0, 'Sugeng'], [73, 1, 'Ndalu'], [74, 0, 'Sugeng'], [74, 1, 'Rawuh'], [75, 0, 'Piye'], [75, 1, 'Kabare?'], [76, 0, 'Pripun'], [76, 1, 'Kabare?'], [77, 0, 'Apik'], [77, 1, 'Matur'], [77, 2, 'Suwun'], [78, 0, 'Sae'], [78, 1, 'Matur'], [78, 2, 'Suwun'], [79, 0, 'Biasa'], [79, 1, 'Wae'], [80, 0, 'Suwe'], [80, 1, 'Ora'], [80, 2, 'Ketemu'], [81, 0, 'Aku'], [81, 1, 'Kangen'], [81, 2, 'Kowe'], [82, 0, 'Ana'], [82, 1, 'Kabar'], [82, 2, 'Apa'], [83, 0, 'Sami-sami'], [84, 0, 'Mangga'], [84, 1, 'Pinarak']
        ],
        "U2P1" => [
            ['Permisi'], ['Permisi'], ['Nama'], ['Nama'], ['Saya'], ['Budi'], ['Adi'], ['Lahir'], ['Di'], ['Surabaya'], ['Anda'], ['Dari'], ['Mana'], ['Sekarang'], ['Sudah'], ['Umur'], ['16'], ['Tahun'], ['Siapa'], ['Siapa'], ['Ayah'], ['Ibu'], ['Rumah'], ['Dimana'],
            ['Kula nuwun'], ['Nuwun sewu'], ['Nami'], ['Asma'], ['Kula'], ['Budi'], ['Adi'], ['Lair'], ['Ing'], ['Suroboyo'], ['Panjenengan'], ['Saking'], ['Pundi'], ['Sakniki'], ['Sampun'], ['Umur'], ['16'], ['Taun'], ['Sopo'], ['Sinten'], ['Bapak'], ['Ibuk'], ['Dalem'], ['Teng pundi'],
        ],
        "U2P2" => [
            [133, 0, 'Permisi'], [133, 1, 'Nama'], [133, 2, 'Saya'], [133, 3, 'Budi'], [134, 0, 'Saya'], [134, 1, 'Lahir'], [134, 2, 'Di'], [134, 3, 'Surabaya'], [135, 0, 'Anda'], [135, 1, 'Dari'], [135, 2, 'Mana?'], [136, 0, 'Nama'], [136, 1, 'Saya'], [136, 2, 'Adi'], [137, 0, 'Nama'], [137, 1, 'Saya'], [137, 2, 'Budi'], [138, 0, 'Umur'], [138, 1, 'Saya'], [138, 2, '16'], [138, 3, 'Tahun'], [139, 0, 'Siapa'], [139, 1, 'Nama'], [139, 2, 'Anda?'], [140, 0, 'Rumah'], [140, 1, '-nya'], [140, 2, 'Anda'], [140, 3, 'Di-'], [140, 4, 'Mana?'], [141, 0, 'Ayah'], [141, 1, 'Di-'], [141, 2, 'Mana?'], [142, 0, 'Ibu'], [142, 1, 'Di-'], [142, 2, 'Mana?'], [143, 0, 'Anda'], [143, 1, 'Lahir'], [143, 2, 'Di-'], [143, 3, 'Mana?'], [144, 0, 'Adi'], [144, 1, 'Ada di'], [144, 2, 'Surabaya'], [145, 0, 'Budi'], [145, 1, 'Ada di'], [145, 2, 'Surabaya'], [146, 0, 'Budi'], [146, 1, 'Di-'], [146, 2, 'Mana?'], [147, 0, 'Adi'], [147, 1, 'Di-'], [147, 2, 'Mana?'], [148, 0, 'Saya'], [148, 1, 'Dari'], [148, 2, 'Surabaya'], [149, 0, 'Nama'], [149, 1, 'Saya'], [149, 2, 'Adi']
        ],
        "U3P1" => [
            ['Pintu'], ['Jendela'], ['Kursi'], ['Meja'], ['Kursi Kecil'], ['Baju'], ['Celana'], ['Celana Panjang'], ['Kasur'], ['Selimut'], ['Gayung'], ['Air'], ['Rumah'], ['Atap'], ['Tangga'], ['Pisau'], ['Mangkok'], ['Cangkul'], ['Pohon'], ['Halaman'], ['Bunga'], ['Rumput'], ['Buah'], ['Daun'], ['Tanah'], ['Batu'], ['Hewan'], ['Ikan'], ['Burung'], ['Motor'], ['Kereta'], ['Perahu'], ['Pesawat'], ['Delman'], ['Uang'], ['Uang'], ['Dinding'], ['Handuk'], ['Nasi'], ['Minyak'], ['Telur'], ['Garam'], ['Satu'], ['Dua'], ['Tiga'], ['Empat'], ['Lima'], ['Enam'], ['Tujuh'], ['Delapan'], ['Sembilan'], ['Sepuluh'], ['Sebelas'], ['Dua Belas'], ['Tiga Belas'], ['Empat Belas'], ['Lima Belas'], ['Enam Belas'], ['Tujuh Belas'], ['Delapan Belas'], ['Sembilan Belas'], ['Dua Puluh'], ['Dua Puluh Satu'], ['Dua Puluh Dua'], ['Dua Puluh Tiga'], ['Dua Puluh Empat'], ['Dua Puluh Lima'], ['Dua Puluh Enam'], ['Tiga Puluh'], ['Tiga Puluh Satu'], ['Empat Puluh'], ['Empat Puluh Satu'], ['Lima Puluh'], ['Lima Puluh Satu'], ['Enam Puluh'], ['Enam Puluh Satu'], ['Tujuh Puluh'], ['Tujuh Puluh Satu'], ['Delapan Puluh'], ['Sembilan Puluh'], ['Ini'], ['Itu'], ['Apa'], ['Berapa'], ['Harga'], ['Bagus'], ['Kokoh'], ['Bersih'], ['Banyak'], ['Banyak'], ['Naik'], ['Naik'], ['Keras'], ['Lembut'], ['Sama'], ['Aku'], ['Ayah'], ['Ibu'], ['Nenek/Kakek'], ['Beli'], ['Beli'],
            ['Lawang'], ['Jendhela'], ['Kursi'], ['Meja'], ['Dingklik'], ['Klambi'], ['Kathok'], ['Celono'], ['Amben'], ['Kemul'], ['Ciduk'], ['Banyu'], ['Omah'], ['Gendheng'], ['Ondo'], ['Piso'], ['Tuwung'], ['Pacul'], ['Wit'], ['Latar'], ['Kembang'], ['Suket'], ['Woh'], ['Godhong'], ['Lemah'], ['Watu'], ['Kewan'], ['Iwak'], ['Manuk'], ['Montor'], ['Sepur'], ['Prau'], ['Montor Mabur'], ['Dokar'], ['Arto'], ['Duwit'], ['Tembok'], ['Anduk'], ['Sego'], ['Lengo'], ['Endog'], ['Uyah'], ['Siji'], ['Loro'], ['Telu'], ['Papat'], ['Limo'], ['Enem'], ['Pitu'], ['Wolu'], ['Sanga'], ['Sepuluh'], ['Sewelas'], ['Rolas'], ['Telulas'], ['Patbelas'], ['Limolas'], ['Nembelas'], ['Pitulas'], ['Wolulas'], ['Sangalas'], ['Rongpuluh'], ['Selikur'], ['Rolikur'], ['Telulikur'], ['Patlikur'], ['Selawe'], ['Nemlikur'], ['Telungpuluh'], ['Telungpuluh Siji'], ['Patangpuluh'], ['Patangpuluh Siji'], ['Seket'], ['Seket Siji'], ['Sewidak'], ['Sewidak Siji'], ['Pitungpuluh'], ['Pitungpuluh Siji'], ['Wolungpuluh'], ['Sangangpuluh'], ['Iki'], ['Iku'], ['Opo'], ['Piro'], ['Rego'], ['Apik'], ['Kuwat'], ['Resik'], ['Akeh'], ['Katah'], ['Nitih'], ['Numpak'], ['Atos'], ['Empuk'], ['Karo'], ['Aku'], ['Bapak'], ['Ibuk'], ['Simbah'], ['Tuku'], ['Tumbas']
        ],
    ];



    // public const soal1 = [
    //     "u2" => [
    //         ['Aku tuku', 'A AY'], ['Aku mangan', 'A AP'], ['Aku mlaku', 'A AK'], ['Aku ndelok', 'A AN'], ['Aku ngerti', 'A AO'], ['Aku ngombe', 'A AQ'], ['Aku krungu', 'A AR'], ['Aku nggawe', 'A AV'], ['Aku lungguh', 'A AW'], ['Aku ngomong', 'A AM'], ['Aku seneng', 'A AT'], ['Aku mandheg', 'A AZ'], ['Aku lara', 'A AB'],
    //         ['Kowe tuku', 'B AY'], ['Kowe mangan', 'B AP'], ['Kowe mlaku', 'B AK'], ['Kowe ndelok', 'B AN'], ['Kowe ngerti?', 'B AO'], ['Kowe ngombe', 'B AQ'], ['Kowe krungu?', 'B AR'], ['Kowe nggawe', 'B AV'], ['Kowe lungguh', 'B AW'], ['Kowe ngomong', 'B AM'], ['Kowe seneng', 'B AT'], ['Kowe mandheg', 'B AZ'], ['Kowe lara', 'B AB'], ['Kowe ngendhi?', 'B I'],
    //         ['Sing ngendhi iku?', 'J F'], ['Sing ngendhi iki?', 'J E'], ['Iki opo?', 'E G'], ['Opo iki?', 'G E'], ['Iku opo?', 'F G'], ['Opo iku?', 'G F'], ['Iki piro?', 'E AG'], ['Iku piro?', 'F AG'], ['Teko kapan?', 'AJ H'], ['Wingi esuk', 'AA AD'], ['Wingi awan', 'AA AE'], ['Wingi bengi', 'AA AF'],

    //     ],
    //     "u3" => [
    //         ['Aku tuku wingi', 'A AY AA'], ['Aku mlaku esuk', 'A AK AD'], ['Kapan kowe teko?', 'H B AJ'],
    //     ],
    //     "ngoko" => [
    //         "1" => [
    //             "1" => Dictionary::vocab['ngoko']["1"],
    //             "2" => [
    //                 ['Aku tuku', 'A AY'], ['Aku mangan', 'A AP'], ['Aku mlaku', 'A AK'], ['Aku ndelok', 'A AN'], ['Aku ngerti', 'A AO'], ['Aku ngombe', 'A AQ'], ['Aku krungu', 'A AR'], ['Aku nggawe', 'A AV'], ['Aku lungguh', 'A AW'], ['Aku ngomong', 'A AM'], ['Aku seneng', 'A AT'], ['Aku mandheg', 'A AZ'], ['Aku lara', 'A AB'],
    //                 ['Kowe tuku', 'B AY'], ['Kowe mangan', 'B AP'], ['Kowe mlaku', 'B AK'], ['Kowe ndelok', 'B AN'], ['Kowe ngerti?', 'B AO'], ['Kowe ngombe', 'B AQ'], ['Kowe krungu?', 'B AR'], ['Kowe nggawe', 'B AV'], ['Kowe lungguh', 'B AW'], ['Kowe ngomong', 'B AM'], ['Kowe seneng', 'B AT'], ['Kowe mandheg', 'B AZ'], ['Kowe lara', 'B AB'], ['Kowe ngendhi?', 'B I'],
    //                 ['Sing ngendhi iku?', 'J F'], ['Sing ngendhi iki?', 'J E'], ['Iki opo?', 'E G'], ['Opo iki?', 'G E'], ['Iku opo?', 'F G'], ['Opo iku?', 'G F'], ['Iki piro?', 'E AG'], ['Iku piro?', 'F AG'], ['Teko kapan?', 'AJ H'], ['Wingi esuk', 'AA AD'], ['Wingi awan', 'AA AE'], ['Wingi bengi', 'AA AF']
    //             ],
    //             "3" => [
    //                 ['Aku tuku wingi', 'A AY AA'], ['Aku mlaku esuk', 'A AK AD'], ['Kapan kowe teko?', 'H B AJ'],
    //             ],
    //         ],
    //     ],

    //     "kromo" => [
    //         "1" => [
    //             "1" => Dictionary::vocab['kromo']['1'],
    //             "2" => [
    //                 ['Sugeng Enjing', '1 2'], ['Sugeng Siang', '1 3'], ['Sugeng Sonten', '1 4'], ['Sugeng Ndalu', '1 5'], ['Sugeng Rawuh', '1 6'],
    //             ],
    //         ],
    //     ]
    // ];
}
